//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pocket.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_al {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_al() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pocket.Languages.lang_al", typeof(lang_al).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buxheti: .
        /// </summary>
        internal static string budget {
            get {
                return ResourceManager.GetString("budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shpenzimi:.
        /// </summary>
        internal static string costexpenses {
            get {
                return ResourceManager.GetString("costexpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgjencë.
        /// </summary>
        internal static string emergency {
            get {
                return ResourceManager.GetString("emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shtesë.
        /// </summary>
        internal static string extra {
            get {
                return ResourceManager.GetString("extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri i plotë.
        /// </summary>
        internal static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndihmë.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushime.
        /// </summary>
        internal static string holidays {
            get {
                return ResourceManager.GetString("holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballina.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kujdes shtëpiak.
        /// </summary>
        internal static string homecare {
            get {
                return ResourceManager.GetString("homecare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string languagesswitch {
            get {
                return ResourceManager.GetString("languagesswitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi.
        /// </summary>
        internal static string loans {
            get {
                return ResourceManager.GetString("loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçu.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçuni nëse keni llogari..
        /// </summary>
        internal static string longsignin {
            get {
                return ResourceManager.GetString("longsignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk keni llogari? Regjistrohu..
        /// </summary>
        internal static string longsignup {
            get {
                return ResourceManager.GetString("longsignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shëndet.
        /// </summary>
        internal static string medical {
            get {
                return ResourceManager.GetString("medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri i llojit të ri.
        /// </summary>
        internal static string newtypename {
            get {
                return ResourceManager.GetString("newtypename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shënime:.
        /// </summary>
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metoda e pagesës:.
        /// </summary>
        internal static string paymentmethod {
            get {
                return ResourceManager.GetString("paymentmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përsërit fjalëkalimin.
        /// </summary>
        internal static string repeatpassword {
            get {
                return ResourceManager.GetString("repeatpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporte.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursime.
        /// </summary>
        internal static string savings {
            get {
                return ResourceManager.GetString("savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regjistrohu.
        /// </summary>
        internal static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totali i të hyrave: .
        /// </summary>
        internal static string totalincome {
            get {
                return ResourceManager.GetString("totalincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreditë: .
        /// </summary>
        internal static string totalloans {
            get {
                return ResourceManager.GetString("totalloans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e shpenzimit:.
        /// </summary>
        internal static string transactiondate {
            get {
                return ResourceManager.GetString("transactiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri i llojit:.
        /// </summary>
        internal static string typename {
            get {
                return ResourceManager.GetString("typename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesi.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shpenzime administrative.
        /// </summary>
        internal static string utilities {
            get {
                return ResourceManager.GetString("utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veshmbathje.
        /// </summary>
        internal static string wardrobe {
            get {
                return ResourceManager.GetString("wardrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirëserdhe, .
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
